name: Deploy Frontend

on:
  push:
    branches: ['main'] # main에 push 될 때만 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Node 빌드 (optional - dockerfile 안에서도 하지만 캐시 활용 위해 추가)
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install & Build
        run: |
          npm install --frozen-lockfile
          npm run build

      # Docker build & push to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/frontend:latest .
          docker push ghcr.io/${{ github.repository }}/frontend:latest

      # SSH 배포
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository }}/frontend:latest
            docker stop frontend || true
            docker rm frontend || true
            docker run -d --name frontend -p 8080:80 ghcr.io/${{ github.repository }}/frontend:latest
